package integration

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestAntigravityFrontmatterContract(t *testing.T) {
	// Create a temporary project directory
	tempDir := t.TempDir()

	// Simulate an existing workflow file without frontmatter (dirty state)
	workflowsDir := filepath.Join(tempDir, ".agents", "workflows")
	err := os.MkdirAll(workflowsDir, 0755)
	if err != nil {
		t.Fatalf("Failed to create workflows dir: %v", err)
	}

	qddWorkflowPath := filepath.Join(workflowsDir, "qdd.md")
	dirtyContent := "### QDD AUTOGENERATED COMMANDS BEGIN ###\nfake rules\n### QDD AUTOGENERATED COMMANDS END ###\n"
	err = os.WriteFile(qddWorkflowPath, []byte(dirtyContent), 0644)
	if err != nil {
		t.Fatalf("Failed to create dirty workflow file: %v", err)
	}

	// Run the Antigravity Sync
	adapter := &AntigravityAdapter{}
	err = adapter.Sync(tempDir)
	if err != nil {
		t.Fatalf("Sync failed: %v", err)
	}

	// Verify the contract: The file MUST contain the description frontmatter
	finalContent, err := os.ReadFile(qddWorkflowPath)
	if err != nil {
		t.Fatalf("Failed to read final workflow file: %v", err)
	}

	finalStr := string(finalContent)
	if !strings.Contains(finalStr, "description:") {
		t.Fatalf("🚨 CONTRATO ROTO: El archivo generado por AntigravityAdapter no contiene el frontmatter 'description:'. Contenido final:\n%s", finalStr)
	}
	
	if !strings.HasPrefix(finalStr, "---") {
		t.Fatalf("🚨 CONTRATO ROTO: El archivo generado debe comenzar estrictamente con '---' para ser válido en el IDE.")
	}

	t.Log("Éxito: El contrato del frontmatter se ha cumplido. El bug está sellado.")
}
