package integration

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestAntigravityFrontmatterContract(t *testing.T) {
	tempDir := t.TempDir()
	qddWorkflowPath := setupDirtyWorkflowFile(t, tempDir)

	adapter := &AntigravityAdapter{}
	err := adapter.Sync(tempDir)
	if err != nil {
		t.Fatalf("Sync failed: %v", err)
	}

	verifyFrontmatterContract(t, qddWorkflowPath)
}

func setupDirtyWorkflowFile(t *testing.T, tempDir string) string {
	workflowsDir := filepath.Join(tempDir, ".agents", "workflows")
	err := os.MkdirAll(workflowsDir, 0755)
	if err != nil {
		t.Fatalf("Failed to create workflows dir: %v", err)
	}

	qddWorkflowPath := filepath.Join(workflowsDir, "qdd.md")
	dirtyContent := "### QDD AUTOGENERATED COMMANDS BEGIN ###\nfake rules\n### QDD AUTOGENERATED COMMANDS END ###\n"
	err = os.WriteFile(qddWorkflowPath, []byte(dirtyContent), 0644)
	if err != nil {
		t.Fatalf("Failed to create dirty workflow file: %v", err)
	}
	return qddWorkflowPath
}

func verifyFrontmatterContract(t *testing.T, qddWorkflowPath string) {
	finalContent, err := os.ReadFile(qddWorkflowPath)
	if err != nil {
		t.Fatalf("Failed to read final workflow file: %v", err)
	}

	finalStr := string(finalContent)
	if !strings.Contains(finalStr, "description:") {
		t.Fatalf("🚨 CONTRATO ROTO: El archivo generado por AntigravityAdapter no contiene el frontmatter 'description:'. Contenido final:\n%s", finalStr)
	}
	
	if !strings.HasPrefix(finalStr, "---") {
		t.Fatalf("🚨 CONTRATO ROTO: El archivo generado debe comenzar estrictamente con '---' para ser válido en el IDE.")
	}

	t.Log("Éxito: El contrato del frontmatter se ha cumplido. El bug está sellado.")
}
