package integration

import (
	"fmt"
	"io/ioutil"
	"os"
	"os/exec"
	"strings"
)

const (
	markerBegin = "### QDD AUTOGENERATED COMMANDS BEGIN ###"
	markerEnd   = "### QDD AUTOGENERATED COMMANDS END ###"
)

// SafeInjectIdempotent injects the QDD Command Protocol into a given file.
// If the file exists, it will replace the block between markerBegin and markerEnd.
// If the block doesn't exist, it appends it to the end.
// If the file does not exist, it creates it.
func SafeInjectIdempotent(filePath string) error {
	content, err := readExistingContent(filePath)
	if err != nil {
		return fmt.Errorf("failed to read %s: %w", filePath, err)
	}

	content = removeOldBlock(content)
	content = appendNewBlock(content)

	if err := ioutil.WriteFile(filePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", filePath, err)
	}

	return nil
}

func readExistingContent(filePath string) (string, error) {
	if _, err := os.Stat(filePath); err == nil {
		bytes, err := ioutil.ReadFile(filePath)
		if err != nil {
			return "", err
		}
		return string(bytes), nil
	}
	return "", nil
}

func removeOldBlock(content string) string {
	beginIdx := strings.Index(content, markerBegin)
	endIdx := strings.Index(content, markerEnd)

	if beginIdx != -1 && endIdx != -1 && endIdx > beginIdx {
		return content[:beginIdx] + content[endIdx+len(markerEnd):]
	}
	return content
}

func appendNewBlock(content string) string {
	content = strings.TrimSpace(content)
	if content != "" {
		content += "\n\n"
	}
	content += strings.TrimSpace(QDDCommandProtocol) + "\n"
	return content
}

// resolveQDDPath returns the absolute path of the qdd binary.
// It prioritizes the current executable, but falls back to exec.LookPath if running via "go run".
func resolveQDDPath() string {
	exe, err := os.Executable()
	if err == nil && !strings.Contains(exe, "/tmp/") && !strings.Contains(exe, "\\Temp\\") {
		return exe
	}

	path, err := exec.LookPath("qdd")
	if err == nil {
		return path
	}

	return "qdd"
}
