trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: awsdeploy

steps:
- checkout: self
  persistCredentials: true

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Instalando Node.js'

- script: |
    npm install
    npm install -g serverless
  displayName: 'Instalando dependencias' 

- bash: | 
    serverless config credentials --provider aws --key $(KEY) --secret  $(SECRET)  
  displayName: 'Estableciendo credenciales'

- script: | 
    npm run remove
  displayName: 'Eliminando el proyecto si existe'

- script: | 
    npm run deploy
  displayName: 'Desplegando el proyecto'
  condition: succeededOrFailed() 