
service: act-api

frameworkVersion: "3"

package:
  individually: true
  exclude:
  - node_modules/**

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies

custom:
  secrets: "${file(secrets_${opt:stage}.json)}"
  customDomain:
    domainName: ${self:custom.secrets.DOMAINNAME}
    basePath: ${self:custom.secrets.BASEPATH}
    stage: ${opt:stage}
    createRoute53Record: true
  serverless-offline:
    useChildProcesses: true
    allowCache: true
provider: 
  endpointType: REGIONAL
  apiName: ${self:custom.secrets.APINAME}
  name: aws
  stage: ${opt:stage}
  runtime: nodejs16.x
  region: ${self:custom.secrets.REGION}
  timeout: 30
  memorySize: 500
  role: arn:aws:iam::221345006153:role/lambda_generico-rol
  vpc:
    securityGroupIds:
      - sg-065652b426ff0db72
    subnetIds:
      - subnet-0dd79e028ea45a040
      - subnet-05313aaa64d91435e
  apiGateway:
    restApiRootResourceId:  "${self:custom.secrets.REST_API_ROOT_RESOURCE_ID}"
    restApiId:  "${self:custom.secrets.REST_API_ID}"
  environment:
    NODE_ENV: "${self:custom.secrets.NODE_ENV}"
    PGUSER: "${self:custom.secrets.PGUSER}"
    PGHOST: "${self:custom.secrets.PGHOST}"
    PGPASSWORD: "${self:custom.secrets.PGPASSWORD}"
    PGDATABASE: "${self:custom.secrets.PGDATABASE}"
    PGPORT: "${self:custom.secrets.PGPORT}"
    APINAME: "${self:custom.secrets.APINAME}"
  layers:
    - arn:aws:lambda:us-east-1:221345006153:layer:pg:1
    - arn:aws:lambda:us-east-1:221345006153:layer:jwt-decode:2
    - arn:aws:lambda:us-east-1:221345006153:layer:moment-timezone:1
    - arn:aws:lambda:us-east-1:221345006153:layer:indicative:2
    - arn:aws:lambda:us-east-1:221345006153:layer:util-header:1

functions:
  - ${file(./src/functions.yml)}
