// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {audit} from '../models';
import {dashboard} from '../models';

export function GetPolicies():Promise<audit.QDDPolicies>;

export function GetState():Promise<dashboard.QDDState>;

export function Intent(arg1:string):Promise<Record<string, any>>;

export function SavePolicies(arg1:audit.QDDPolicies):Promise<Record<string, string>>;
