// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPolicies() {
  return window['go']['main']['App']['GetPolicies']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function Intent(arg1) {
  return window['go']['main']['App']['Intent'](arg1);
}

export function SavePolicies(arg1) {
  return window['go']['main']['App']['SavePolicies'](arg1);
}
